### ISSUE TITLE
Error when using worktrees

### ISSUE THREAD

**Issue by mbeniamino** [comelz/quark#28]
It seems that in worktrees .git is not a directory, but a text file containing a reference:

> gitdir: /home/lbonato/comelz/caligola/caligola3d/.git/worktrees/build-19.04

This causes an exception when quark tries to create/modify the ignore file for the sandbox.

```
Traceback (most recent call last):
 File "/home/lbonato/bin/quark", line 25, in <module>
   main()
 File "/home/lbonato/bin/quark", line 18, in main
   fn()
 File "/home/lbonato/quark/bin/../quark/update.py", line 44, in run
   generate_cmake_script(source_dir, print_tree=optlist.verbose, options=options, clean=optlist.clean)
 File "/home/lbonato/quark/bin/../quark/subproject.py", line 570, in generate_cmake_script
   root, modules = Subproject.create_dependency_tree(source_dir, url, options, update=update, clean=clean)
 File "/home/lbonato/quark/bin/../quark/subproject.py", line 193, in create_dependency_tree
   root.set_local_ignores(subprojects_dir, modules.values())
 File "/home/lbonato/quark/bin/../quark/subproject.py", line 399, in set_local_ignores
   os.makedirs(exclude_path_dir, exist_ok = True)
 File "/usr/lib/python3.5/os.py", line 241, in makedirs
   mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/home/lbonato/comelz/caligola/olds/build-19.04/.git/info'
```

**Comment by naufraghi** [comment]
Should be solved in https://github.com/comelz/quark/pull/29 (I use worktrees a lot and `quark` works)

**Comment by cvtsi2sd** [comment]
Indeed. I also checked if more modern git gained some per-worktree exclude file, but the situation didn't change, so we cannot do much better than that. Closing.
